version: '3'

services:
    server:
        container_name: POC_ORDER_API
        build: '.'
        volumes:
            - ./:/node-app
            - ./node_modules:/node-app/node_modules
        environment: 
            NODE_ENV: development
        depends_on: 
            - db
        links:
            - db
        ports:
            - '3334:3334'
            - '9229:9229'
        command: npm run start:dev

    db:
        image: 'mongo'
        container_name: POC_ORDER_API_MONGO
        ports:
            - '27017:27017'